### ISSUE TITLE
2014 Regulations and TNoodle

### ISSUE THREAD

**Issue by lgarron** [thewca/tnoodle#150]
Things that TNoodle needs to have for 2014:
- [x] Skewb (#122)
- [x] BLD orientation/wide turns (#148)
- [ ] Square One optimal solver (#151, #153)
- [x] Switch clock colors (#154)

Low-priority (does not need to be ready Jan. 1):
- [x] Link for regenerating scrambles (#134)
- [ ] Old-stye clock scrambles below new ones (#149)
